"""Configuration constants for lightweight quick-scan analysis."""

QUICK_SCAN_DEPTH = 8
QUICK_SCAN_TIME_MS = 60
QUICK_SCAN_CONCURRENCY = 2
QUICK_SCAN_CP_THRESHOLD = 100
QUICK_SCAN_MAX_GAMES = 250
MAX_CONCURRENT_SCANS = 1
